### ISSUE TITLE
A13 Olinuxino hang in u-boot

### ISSUE THREAD

**Issue by dansmolik** [linux-sunxi/u-boot-sunxi#27] opened 2013-03-29 22:56 UTC
I have found  hang problem with latest u-boot. I checkout latest u-boot sunxi source from git and compile and install. All works fine. But I found problem when enter reset command to u-boot prompt second time system hang. I try debug problem add some puts("reset") to arch/arm/lib/reset.c and see that reset_cpu(0) is entered but system doesn't reboot but hang.
Scenario:
Power on board -> press a key to enter prompt -> type reset enter -> system is resetting ->
press a key to enter prompt -> type reset enter -> HANG.

I found workaround uncomment in include/configs/sunxi-common.h   
# define CONFIG_WATCHDOG  solve the problem.

Regards Dan

**Comment by nvdl** [comment] 2013-03-30 22:08
@dansmolik: I tried the approach but is not helping me. Did you do something else as well?

**Comment by dansmolik** [comment] 2013-03-31 00:54
Sorry I don't understand you very well. Did you try my procedure ? Do you have Olinuxino A13 ?

**Comment by nvdl** [comment] 2013-03-31 01:17
Yes, I have this board and compiled the source after changing the header file.
Can you share the binary files from u-boot compilation?

**Comment by dansmolik** [comment] 2013-03-31 06:34
Nvd napsal(a):

> Yes, I have this board and compiled the source after changing the header file.
> Can you share the binary files from u-boot compilation?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/linux-sunxi/u-boot-sunxi/issues/27#issuecomment-15684950.
> 
> Yes there it is.

Dan

## 

Mydatex s r.o.
http://www.mydatex.cz
email: smolik@mydatex.cz
mob: 604200362
tel: 226210085

**Comment by nvdl** [comment] 2013-03-31 12:56
Sorry, but I cannot see any link to the binaries.

**Comment by dansmolik** [comment] 2013-04-01 15:16
My fault, I attach only to email. There is link http://www.mydatex.cz/bug/u-boot-A13-hang.tgz

**Comment by nvdl** [comment] 2013-04-04 00:14
@dansmolik: Thanks for the binaries but it does not fix the problem.
Looks like more changes are needed.
Can you please share the contents of the first partition of the uSD card?

Files and directories:
boot.axf  boot.ini  boot.scr  linux  script.bin  sprite.axf

And the kernel configuration:
zcat /proc/config.gz > config

Is the Linux image, that you are using, downloadable from the net?

**Comment by dansmolik** [comment] 2013-04-04 05:34
Yes I send you everything you need including linux image. But I am on holiday and will be back on Sunday :-)
Please be patient.

**Comment by dansmolik** [comment] 2013-04-09 08:19
Nvd napsal(a):

> @dansmolik https://github.com/dansmolik: Thanks for the binaries but it does not fix the problem.
> Looks like more changes are needed.
> Can you please share the contents of the first partition of the uSD card?
> 
> Files and directories:
> boot.axf boot.ini boot.scr linux script.bin sprite.axf
> 
> And the kernel configuration:
> zcat /proc/config.gz > config
> 
> Is the Linux image, that you are using, downloadable from the net?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/linux-sunxi/u-boot-sunxi/issues/27#issuecomment-15873463.
> 
> Yes,
> there is all what you want.
> http://www.mydatex.cz/bug/SD_contetnt.tgz

Regards
    Dan

## 

Mydatex s r.o.
http://www.mydatex.cz
email: smolik@mydatex.cz
mob: 604200362
tel: 226210085

**Comment by nvdl** [comment] 2013-04-09 22:00
Still cannot recreate it.

Compiled a kernel and its modules based on the "config" file you provided. Used the binaries for u-boot as provided. Wrote the u-boot binaries to the sectors.
(the board does not boot)

Tried my kernel and the provided u-boot binaries. Wrote the u-boot binaries to the sectors.
(boots but does not fix the "reboot" issue)

I forgot to ask the version of kernel. I compiled the kernel using 3.0.67+ branch.

There are many variables to handle. As a last resort, can you please share the whole image of the uSD card?
There has been a discussion on a group and some people point towards the hardware problem but it does not seems so.

**Comment by dansmolik** [comment] 2013-04-09 22:11
Nvd napsal(a):

> Still cannot recreate it.
> 
> Compiled a kernel and its modules based on the "config" file you provided. Used the binaries for u-boot as provided.
> Wrote the u-boot binaries to the sectors.
> (the board does not boot)
> 
> Tried my kernel and the provided u-boot binaries. Wrote the u-boot binaries to the sectors.
> (boots but does not fix the "reboot" issue)
> 
> There are many variables to handle. As a last resort, can you please share the whole image of the uSD card?
> There has been a discussion on a group and some people point towards the hardware problem but it does not seems so.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/linux-sunxi/u-boot-sunxi/issues/27#issuecomment-16143162.
> 
> Yes no problem. Will be enough 1. partiotion ? I have 2G card for booting and first partition is 16M.
> I will make image with dd.

Regards
    Dan

## 

Mydatex s r.o.
http://www.mydatex.cz
email: smolik@mydatex.cz
mob: 604200362
tel: 226210085

**Comment by nvdl** [comment] 2013-04-09 22:15
Yes, just "dd" the whole card and not 1st or the 2nd partition:

dd if=/dev/mmcblk0 of=/mnt/drive/sd.img bs=1M
sync

Thanks again.

**Comment by dansmolik** [comment] 2013-04-09 22:29
Nvd napsal(a):

> Yes, just "dd" the whole card and not 1st or the 2nd partition:
> 
> dd if=/dev/mmcblk0 of=sd.img bs=1M
> sync
> 
> Thanks again.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/linux-sunxi/u-boot-sunxi/issues/27#issuecomment-16143845.
> 
> Ok. I use only first partition to network boot. I use root on NFS.

Dan

## 

Mydatex s r.o.
http://www.mydatex.cz
email: smolik@mydatex.cz
mob: 604200362
tel: 226210085

**Comment by dansmolik** [comment] 2013-04-10 12:40
Nvd napsal(a):

> Yes, just "dd" the whole card and not 1st or the 2nd partition:
> 
> dd if=/dev/mmcblk0 of=sd.img bs=1M
> sync
> 
> Thanks again.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/linux-sunxi/u-boot-sunxi/issues/27#issuecomment-16143845.
> 
> http://www.mydatex.cz/bug/sd.img.gz
> There it is.

Dan

## 

Mydatex s r.o.
http://www.mydatex.cz
email: smolik@mydatex.cz
mob: 604200362
tel: 226210085

**Comment by nvdl** [comment] 2013-04-11 07:43
Thanks. Will see how it goes.

**Comment by hno** [comment] 2013-04-28 18:53
I can reproduce this easily. Fixing it should be easy.

**Comment by nvdl** [comment] 2013-04-28 19:06
@hno: Are you sure that there is no problem with the A13 itself.

I enabled the watch dog in u-boot by editing "include/configs/sunxi-common.h":

CONFIG_WATCHDOG: defined

"boot_mmc=fatload mmc 0 0x43000000 script.bin && fatload mmc 0 0x48000000 ${kernel} && watchdog 20 && bootm 0x48000000\0"

It caused the system to hang before everything could be online possibly because the kernel was not resetting it.
But, it caused a hung A13 and did not end up in an endless reboot loop.

Now, I am using u-boot with "CONFIG_WATCHDOG" defined but watchdog is not started at u-boot level "watchdog 0".
Reboot does not work though; A13 just gets stuck if "reboot" is issued.
Manual power cycling is needed.

Is there something else that is missing? "script.bin"?

Board: OlinuXino A13.

**Comment by hno** [comment] 2013-04-28 20:24
Now fixed in sunxi-current branch.

**Closed as completed by hno** 2013-04-28 20:24 UTC

**Comment by hno** [comment] 2013-04-28 20:31
There is likely a silicon bug lurking in the watchdog part, but the way u-boot used the watchdog to trigger a system reset was not correct and sometimes be ignored by the silicon resulting in that th CPU is not reset. The kernel very likely have the same issue.

But it is very odd if it hang at timeout if you booted with watchdog enabled in u-boot but no kernel support. I don't see how that can happen.

**Comment by nvdl** [comment] 2013-04-28 20:38
"possibly because the kernel was not resetting it":
I referred to the reset of watchdog.

I am using kernel with watchdog support enabled.

CONFIG_WATCHDOG=y
CONFIG_SOFT_WATCHDOG=m

But, it seems that something is missing and watchdog is not reset within 20 seconds during the boot up.

I am not that much clear about how the watchdog stuff works in u-boot and kernel.

I will give "sunxi-current" a try.

**Comment by hno** [comment] 2013-04-28 20:45
CONFIG_SOFT_WATCHDOG is not the sunxi watchdog. To enable kernel support for the sunxi watchdog you need CONFIG_SUNXI_WDT=y

In addition you need something kicking the watchdog from userspace (/dev/watchdog). The kernel do not do this automatically.
